dist: trusty

before_install:
  - sudo apt-get install -y postgresql postgis gdal-bin qgis python-pyspatialite python-psycopg2

before_script:
  - python package.py -i

script:
  - PYTHONPATH=~/.qgis2/python/plugins python -m qgis_versioning.test || PYTHONPATH=~/.qgis2/python/plugins python -m qgis_versioning.test -v
